### ISSUE TITLE
As a user, i need to be able to use this tool in Microsoft Windows, so that i can use it at my work pc.

### ISSUE THREAD

**Issue by dingjimmy** [dingjimmy/csvtool#4]
## Platform
- Windows 7 +
- .Net 4.6.1
- WPF App

## **ToDo**

- [x] File, New, WPF Project

- [x] Setup App framework: Caliburn.Micro.

- [x] Setup Dependancy Injection: Ninject

- [x] Setup Logging: log4net

- [x] Setup Configurable Options/Feature Toggles:

**Comment by dingjimmy** [comment]
Resolved in pull-request #5
